### ISSUE TITLE
数据库连接错误：failed to connect to server [119.29.162.34:27017] on first connect

### ISSUE THREAD

**Issue by YuxinChou** [k-dylan/easyclub#6]
你好，我遇到一个数据库连接错误，如下：
```
{ MongoError: failed to connect to server [119.29.162.34:27017] on first connect [MongoError: connect ECONNREFUSED 119.29.162.34:27017]
    at Pool.<anonymous> (/Users/yuxin/Downloads/easyclub-master/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/Users/yuxin/Downloads/easyclub-master/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:316:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/Users/yuxin/Downloads/easyclub-master/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'failed to connect to server [119.29.162.34:27017] on first connect [MongoError: connect ECONNREFUSED 119.29.162.34:27017]' }
(node:56695) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [119.29.162.34:27017] on first connect [MongoError: connect ECONNREFUSED 119.29.162.34:27017]
(node:56695) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:56695) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: session store is unavailable
```

配置文件config.js，我只是换了IP，其他没做。

请问如何解决这个问题？谢谢。

**Comment by YuxinChou** [comment]
解决方法如下：
设置其他客户端连接，默认安装的话, 只允许127.0.0.1的IP连接, 需要修改/etc/mongod.conf, 
```
sudo vim /etc/mongod.conf
```
注释掉记录
```
#bind_ip = 127.0.0.1
```
